9812-ERROR-Game Crash at Sun Jan 16 21:56:11 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 107, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 86, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 63, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 84, in update_game_state
    info_getter = engine.gameplay.handle_gameplay(p1_blob, p2_blob, ruleset, settings, p1_is_cpu, p2_is_cpu, timer)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\gameplay.py", line 216, in handle_gameplay
    reset_round()
TypeError: reset_round() missing 1 required positional argument: 'ruleset'
Game State: casual_match
P1 Blob: quirkless, is CPU: False
P2_Blob: quirkless, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

16068-ERROR-Game Crash at Mon Jan 17 08:47:54 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 107, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 86, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 63, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 84, in update_game_state
    info_getter = engine.gameplay.handle_gameplay(p1_blob, p2_blob, ruleset, settings, p1_is_cpu, p2_is_cpu, timer)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\gameplay.py", line 156, in handle_gameplay
    p1_blob = ball.check_blob_collisions(p1_blob)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\ball.py", line 94, in check_blob_collisions
    if(not blob.collision_timer) or (blob.kicked_timer and self.bounciness > 0.1):
AttributeError: 'Blob' object has no attribute 'kicked_timer'
Game State: casual_match
P1 Blob: quirkless, is CPU: False
P2_Blob: quirkless, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

14140-ERROR-Game Crash at Mon Jan 17 11:18:39 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 107, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 66, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 102, in handle_graphics
    draw_settings_screen(game_surface, the_settings, selector_position)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_settings.py", line 21, in draw_settings_screen
    ui_mode_text = "Top" if settings['ui_mode'] else "Bottom"
KeyError: 'ui_mode'
Game State: settings
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

17196-ERROR-Game Crash at Mon Jan 17 12:50:45 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 107, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 66, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 104, in handle_graphics
    draw_rebind_screen(game_surface, settings, info_getter[1])
IndexError: list index out of range
Game State: rebind
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

8780-ERROR-Game Crash at Mon Jan 17 12:51:23 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 107, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 66, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 104, in handle_graphics
    draw_rebind_screen(game_surface, settings, info_getter)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_settings.py", line 51, in draw_rebind_screen
    menu_text = menu_font.render('REBINDING: ' + rebind_key, False, text_color)
TypeError: can only concatenate str (not "list") to str
Game State: rebind
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

11344-ERROR-Game Crash at Mon Jan 17 13:01:51 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 107, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 66, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 104, in handle_graphics
    draw_rebind_screen(game_surface, settings, info_getter)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_settings.py", line 65, in draw_rebind_screen
    text_array.insert(len(text_array//2), menu_font.render("Rebind P2", False, text_color))
TypeError: unsupported operand type(s) for //: 'list' and 'int'
Game State: rebind
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

14440-ERROR-Game Crash at Mon Jan 17 13:30:42 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 107, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 86, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 63, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 124, in update_game_state
    game_state, info_getter = engine.rebind.rebind_menu()
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\rebind.py", line 57, in rebind_menu
    return game_state, [rebind_key, selector_position]
UnboundLocalError: local variable 'selector_position' referenced before assignment
Game State: rebind
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2528-ERROR-Game Crash at Mon Jan 17 13:31:08 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 107, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 86, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 63, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 124, in update_game_state
    game_state, info_getter = engine.rebind.rebind_menu()
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\rebind.py", line 58, in rebind_menu
    return game_state, [rebind_key, selector_position]
UnboundLocalError: local variable 'selector_position' referenced before assignment
Game State: rebind
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

13968-ERROR-Game Crash at Mon Jan 17 14:15:49 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 124, in update_game_state
    game_state, info_getter = engine.rebind.rebind_menu()
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\rebind.py", line 76, in rebind_menu
    game_state, rebind_key = handle_rebinding()
TypeError: handle_rebinding() missing 1 required positional argument: 'rebind_start'
Game State: rebind
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

10888-ERROR-Game Crash at Mon Jan 17 14:38:46 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 124, in update_game_state
    game_state, info_getter = engine.rebind.rebind_menu()
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\rebind.py", line 76, in rebind_menu
    rebind_key = handle_rebinding()
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\rebind.py", line 27, in handle_rebinding
    if(bind_input(rebind_array[rebind_number])):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\handle_input.py", line 104, in bind_input
    for event in get_events:
TypeError: 'function' object is not iterable
Game State: rebind
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

14820-ERROR-Game Crash at Mon Jan 24 15:08:03 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 112, in handle_graphics
    draw_blob_info(game_surface, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 38, in draw_blob_info
    selector_position = info_getter[0]
IndexError: list index out of range
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

16532-ERROR-Game Crash at Mon Jan 24 15:12:11 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 112, in handle_graphics
    draw_blob_info(game_surface, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 39, in draw_blob_info
    ghost_position = info_getter[1]
IndexError: list index out of range
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

15368-ERROR-Game Crash at Mon Jan 31 10:54:39 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 134, in update_game_state
    game_state, info_getter = engine.menus.blob_info_menu.general_navigation()
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 85, in general_navigation
    info_getter = [selector_position, selector_ghost]
UnboundLocalError: local variable 'selector_ghost' referenced before assignment
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

10260-ERROR-Game Crash at Wed Feb  2 21:39:22 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 134, in update_game_state
    game_state, info_getter = engine.menus.blob_info_menu.general_navigation()
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 124, in general_navigation
    blob_info_navigation(pressed, mouse)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 86, in blob_info_navigation
    blob_tab += 1
TypeError: can only concatenate str (not "int") to str
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

7744-ERROR-Game Crash at Mon Feb  7 07:12:38 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 112, in handle_graphics
    draw_blob_info(game_surface, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 129, in draw_blob_info
    draw_blob_info(game_display, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 129, in draw_blob_info
    draw_blob_info(game_display, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 129, in draw_blob_info
    draw_blob_info(game_display, info_getter, settings)
  [Previous line repeated 991 more times]
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 126, in draw_blob_info
    draw_background(game_display, 'green_background', settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\background_handler.py", line 62, in draw_background
    if not (game_screen == previous_game_screen):
RecursionError: maximum recursion depth exceeded in comparison
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

15080-ERROR-Game Crash at Mon Feb  7 07:17:13 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 112, in handle_graphics
    draw_blob_info(game_surface, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 129, in draw_blob_info
    draw_blob_selector(game_display, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 78, in draw_blob_selector
    game_display.blit(ghost, ((ghost_position[0] + 0.85) * 170, (ghost_position[1] + 0.5) * 100))
UnboundLocalError: local variable 'ghost' referenced before assignment
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

17828-ERROR-Game Crash at Mon Feb  7 10:46:49 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 134, in update_game_state
    game_state, info_getter = engine.menus.blob_info_menu.general_navigation()
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 126, in general_navigation
    game_state = blob_selector_navigation(pressed, mouse)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 46, in blob_selector_navigation
    load_individual_blob(selector_position)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 52, in load_individual_blob
    selected_blob_image = pg.image.load(selected_blob[0])
FileNotFoundError: No such file or directory.
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2816-ERROR-Game Crash at Mon Feb  7 10:47:34 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 134, in update_game_state
    game_state, info_getter = engine.menus.blob_info_menu.general_navigation()
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 126, in general_navigation
    game_state = blob_selector_navigation(pressed, mouse)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 74, in blob_selector_navigation
    load_individual_blob(selector_position)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 52, in load_individual_blob
    selected_blob_image = pg.image.load(cwd + selected_blob[0])
FileNotFoundError: No such file or directory.
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

12984-ERROR-Game Crash at Mon Feb  7 11:33:07 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 134, in update_game_state
    game_state, info_getter = engine.menus.blob_info_menu.general_navigation()
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 126, in general_navigation
    game_state = blob_selector_navigation(pressed, mouse)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 74, in blob_selector_navigation
    load_individual_blob(selector_position)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 59, in load_individual_blob
    selected_blob_description = find_blob_unlock(selected_blob[2])[2]
TypeError: 'NoneType' object is not subscriptable
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

12244-ERROR-Game Crash at Mon Feb  7 11:46:25 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 134, in update_game_state
    game_state, info_getter = engine.menus.blob_info_menu.general_navigation()
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 126, in general_navigation
    game_state = blob_selector_navigation(pressed, mouse)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 74, in blob_selector_navigation
    load_individual_blob(selector_position)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 62, in load_individual_blob
    selected_blob_stars = species_to_stars(selected_blob[2])
TypeError: species_to_stars() missing 1 required positional argument: 'stat_overrides'
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

17444-ERROR-Game Crash at Mon Feb  7 11:59:32 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 112, in handle_graphics
    draw_blob_info(game_surface, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 270, in draw_blob_info
    draw_blob_page(game_display, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 260, in draw_blob_page
    page_directory[blob_tab](game_display)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 213, in blob_page_1
    menu_font.render("HP: " + str(selected_blob_matchups['max_hp']), False, text_color),
KeyError: 'max_hp'
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1332-ERROR-Game Crash at Mon Feb 14 08:09:44 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 112, in handle_graphics
    draw_blob_info(game_surface, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 315, in draw_blob_info
    draw_blob_page(game_display, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 305, in draw_blob_page
    page_directory[blob_tab](game_display)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 228, in blob_page_2
    menu_font.render("HP: " + str(selected_blob_stars['max_hp'] + "*"), False, text_color),
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

9500-ERROR-Game Crash at Mon Feb 14 12:31:50 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 112, in handle_graphics
    draw_blob_info(game_surface, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 331, in draw_blob_info
    draw_blob_page(game_display, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 321, in draw_blob_page
    page_directory[blob_tab](game_display)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 282, in blob_page_5
    for text_box in selected_blob_tips:
TypeError: 'NoneType' object is not iterable
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

16308-ERROR-Game Crash at Mon Feb 14 14:02:06 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 136, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(timer)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\medal_milestone_menu.py", line 49, in medal_navigation
    medal_selected = game_state_navigation(selector_position)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\main_menu.py", line 34, in game_state_navigation
    return game_state[selector_position]
KeyError: (0, 0)
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

14028-ERROR-Game Crash at Mon Feb 14 14:02:16 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 136, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(timer)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\medal_milestone_menu.py", line 49, in medal_navigation
    medal_selected = game_state_navigation(selector_position)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\main_menu.py", line 34, in game_state_navigation
    return game_state[selector_position]
KeyError: (0, 0)
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

11200-ERROR-Game Crash at Mon Mar  7 12:49:56 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 112, in handle_graphics
    draw_blob_info(game_surface, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 339, in draw_blob_info
    if not selector_position[2]:
TypeError: 'int' object is not subscriptable
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

25392-ERROR-Game Crash at Mon Mar  7 13:32:32 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 112, in handle_graphics
    draw_blob_info(game_surface, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 353, in draw_blob_info
    draw_blob_page(game_display, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 328, in draw_blob_page
    game_display.blit(info_ball, (1000, 76 + (66 * blob_tab)))
TypeError: argument 1 must be pygame.Surface, not None
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1224-ERROR-Game Crash at Mon Mar  7 13:50:18 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 112, in handle_graphics
    draw_blob_info(game_surface, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 370, in draw_blob_info
    draw_blob_selector(game_display, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 100, in draw_blob_selector
    menu_font.render("INSTRUCTIONS: Use movement keys", False, (0, 0, 255)),
UnboundLocalError: local variable 'menu_font' referenced before assignment
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

16832-ERROR-Game Crash at Mon Mar  7 14:06:22 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 72, in handle_graphics
    draw_main_menu(game_surface, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_main_menu.py", line 15, in draw_main_menu
    menu_font.render('Play!', False, (0, 0, 150)),
NameError: name 'menu_font' is not defined
Game State: main_menu
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

19960-ERROR-Game Crash at Mon Mar  7 14:27:35 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "main.py", line 108, in <module>
    game_state = run(game_state)
  File "main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 110, in handle_graphics
    draw_almanac_main(game_surface, selector_position, settings)
  File "C:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_almanac.py", line 79, in draw_almanac_main
    text_array = static_text['almanac_main']
KeyError: 'almanac_main'
Game State: almanac
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

13636-ERROR-Game Crash at Mon Mar  7 14:30:47 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 110, in handle_graphics
    draw_almanac_main(game_surface, selector_position, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_almanac.py", line 83, in draw_almanac_main
    text_array = static_text['almanac_main']
KeyError: 'almanac_main'
Game State: almanac
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

21648-ERROR-Game Crash at Mon Mar  7 14:32:33 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 110, in handle_graphics
    draw_almanac_main(game_surface, selector_position, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_almanac.py", line 83, in draw_almanac_main
    text_array = static_text['almanac_main']
KeyError: 'almanac_main'
Game State: almanac
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

8788-ERROR-Game Crash at Mon Mar  7 14:32:46 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 110, in handle_graphics
    draw_almanac_main(game_surface, selector_position, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_almanac.py", line 87, in draw_almanac_main
    ball_76 = pg.transform.scale(ball, (76, 76))
TypeError: argument 1 must be pygame.Surface, not None
Game State: almanac
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

23064-ERROR-Game Crash at Mon Mar  7 14:35:09 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 110, in handle_graphics
    draw_almanac_main(game_surface, selector_position, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_almanac.py", line 82, in draw_almanac_main
    text_array = static_text['almanac_main']
KeyError: 'almanac_main'
Game State: almanac
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

12588-ERROR-Game Crash at Mon Mar  7 14:35:44 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 108, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 110, in handle_graphics
    draw_almanac_main(game_surface, selector_position, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_almanac.py", line 82, in draw_almanac_main
    text_array = static_text['almanac_main']
KeyError: 'almanac_main'
Game State: almanac
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

5872-ERROR-Game Crash at Sun Mar 13 00:04:25 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 88, in handle_graphics
    draw_gameplay(screen_size, game_surface, p1_blob, p2_blob, ball, game_score, timer, game_time, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_gameplay.py", line 371, in draw_gameplay
    draw_ui(screen_size, gameplay_surface, p1_blob, p2_blob)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_gameplay.py", line 138, in draw_ui
    if not (image_cache['ui_initialized']):
KeyError: 'ui_initialized'
Game State: casual_match
P1 Blob: quirkless, is CPU: False
P2_Blob: quirkless, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

8972-ERROR-Game Crash at Sun Mar 13 00:06:25 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 88, in handle_graphics
    draw_gameplay(screen_size, game_surface, p1_blob, p2_blob, ball, game_score, timer, game_time, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_gameplay.py", line 372, in draw_gameplay
    draw_ui(screen_size, gameplay_surface, p1_blob, p2_blob)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_gameplay.py", line 139, in draw_ui
    if not (image_cache['ui_initialized']):
KeyError: 'ui_initialized'
Game State: casual_match
P1 Blob: quirkless, is CPU: False
P2_Blob: quirkless, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

9252-ERROR-Game Crash at Sun Mar 13 00:07:05 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 88, in handle_graphics
    draw_gameplay(screen_size, game_surface, p1_blob, p2_blob, ball, game_score, timer, game_time, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_gameplay.py", line 371, in draw_gameplay
    draw_ui(screen_size, gameplay_surface, p1_blob, p2_blob)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_gameplay.py", line 139, in draw_ui
    image_cache['p1_ui_icons'] = create_ui_icons(game_display, ui_font, p1_blob, 10)
TypeError: create_ui_icons() takes 2 positional arguments but 4 were given
Game State: casual_match
P1 Blob: quirkless, is CPU: False
P2_Blob: quirkless, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

10804-ERROR-Game Crash at Sun Mar 13 00:16:57 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 88, in handle_graphics
    draw_gameplay(screen_size, game_surface, p1_blob, p2_blob, ball, game_score, timer, game_time, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_gameplay.py", line 342, in draw_gameplay
    image_cache['p2_blob'].fill((150, 150, 150, 255), special_flags=pg.BLEND_RGBA_MULT)
KeyError: 'p2_blob'
Game State: casual_match
P1 Blob: quirkless, is CPU: False
P2_Blob: quirkless, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

17960-ERROR-Game Crash at Sun Mar 13 18:40:16 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 137, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(timer)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\medal_milestone_menu.py", line 49, in medal_navigation
    medal_selected = game_state_navigation(selector_position)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\main_menu.py", line 35, in game_state_navigation
    return game_state[selector_position]
KeyError: (0, 0)
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

17552-ERROR-Game Crash at Mon Mar 14 09:52:38 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 114, in handle_graphics
    draw_almanac_main(game_surface, selector_position, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_almanac.py", line 83, in draw_almanac_main
    text_array = static_text['almanac_main']
KeyError: 'almanac_main'
Game State: almanac
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

10804-ERROR-Game Crash at Mon Mar 14 09:53:31 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 114, in handle_graphics
    draw_almanac_main(game_surface, selector_position, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_almanac.py", line 83, in draw_almanac_main
    text_array = static_text['almanac_main']
KeyError: 'almanac_main'
Game State: almanac
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

15320-ERROR-Game Crash at Mon Mar 14 09:58:19 2022 (Version 0.13.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 88, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 68, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_graphics.py", line 114, in handle_graphics
    draw_almanac_main(game_surface, selector_position, settings)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_almanac.py", line 84, in draw_almanac_main
    text_array = static_text['almanac_main']
KeyError: 'almanac_main'
Game State: almanac
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

20488-ERROR-Game Crash at Thu Mar 17 09:55:35 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 134, in update_game_state
    game_state, info_getter = engine.menus.blob_info_menu.general_navigation()
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 136, in general_navigation
    game_state = blob_selector_navigation(pressed, mouse)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 80, in blob_selector_navigation
    load_individual_blob(selector_position)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 65, in load_individual_blob
    selected_blob_matchups = load_mu_chart()[selected_blob[2]]
KeyError: 'fisher'
Game State: blob_info
P1 Blob: quirkless, is CPU: False
P2_Blob: mirror, is CPU: True

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

14616-ERROR-Game Crash at Thu Mar 17 10:01:21 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\game_handler.py", line 134, in update_game_state
    game_state, info_getter = engine.menus.blob_info_menu.general_navigation()
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 136, in general_navigation
    game_state = blob_selector_navigation(pressed, mouse)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\menus\blob_info_menu.py", line 80, in blob_selector_navigation
    load_individual_blob(selector_position)
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\resources\graphics_engine\display_blob_info.py", line 71, in load_individual_blob
    selected_blob_tips = return_selected_blob_tips(selected_blob[2])
  File "c:\Users\Elijah McLaughlin\Desktop\Python Projects\Blob_Ball\blob_ball\engine\blob_tips.py", line 211, in return_selected_blob_tips
    return tips_dict[selected_blob]
KeyError: 'fisher'
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

3980-ERROR-Game Crash at Tue Mar 22 18:32:21 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 137, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(timer)
TypeError: medal_navigation() missing 2 required positional arguments: 'selector' and 'timer'
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

5904-ERROR-Game Crash at Tue Mar 22 18:38:30 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 137, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(timer)
TypeError: medal_navigation() missing 2 required positional arguments: 'selector' and 'timer'
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2660-ERROR-Game Crash at Tue Mar 22 18:41:17 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 137, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(timer)
TypeError: medal_navigation() missing 2 required positional arguments: 'selector' and 'timer'
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

5560-ERROR-Game Crash at Tue Mar 22 18:51:45 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 137, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(timer)
TypeError: medal_navigation() missing 2 required positional arguments: 'selector' and 'timer'
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

3660-ERROR-Game Crash at Tue Mar 22 18:54:56 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 137, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(timer)
TypeError: medal_navigation() missing 2 required positional arguments: 'selector' and 'timer'
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2580-ERROR-Game Crash at Tue Mar 22 19:19:48 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 137, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(timer)
TypeError: medal_navigation() missing 2 required positional arguments: 'selector' and 'timer'
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

12508-ERROR-Game Crash at Tue Mar 22 19:21:51 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 138, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer)
TypeError: medal_navigation() missing 1 required positional argument: 'timer'
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

7796-ERROR-Game Crash at Tue Mar 22 19:24:06 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 138, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer, timer)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\menus\medal_milestone_menu.py", line 52, in medal_navigation
    if(selector[2] == 0):
TypeError: 'int' object is not subscriptable
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

11212-ERROR-Game Crash at Tue Mar 22 19:27:15 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 138, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer, timer)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\menus\medal_milestone_menu.py", line 52, in medal_navigation
    if(selector[2] == 0):
TypeError: 'int' object is not subscriptable
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

8348-ERROR-Game Crash at Tue Mar 22 19:30:28 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 139, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer, timer)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\menus\medal_milestone_menu.py", line 52, in medal_navigation
    if(selector[2] == 0):
TypeError: 'int' object is not subscriptable
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

5772-ERROR-Game Crash at Tue Mar 22 19:46:30 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 139, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer, timer)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\menus\medal_milestone_menu.py", line 53, in medal_navigation
    if(selector[2] == 0):
TypeError: 'int' object is not subscriptable
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

12024-ERROR-Game Crash at Tue Mar 22 19:46:56 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 139, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer, timer)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\menus\medal_milestone_menu.py", line 53, in medal_navigation
    if(selector[2] == 0):
TypeError: 'int' object is not subscriptable
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

12912-ERROR-Game Crash at Tue Mar 22 19:53:09 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 139, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer, timer)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\menus\medal_milestone_menu.py", line 53, in medal_navigation
    if(medal_selector[2] == 0):
TypeError: 'int' object is not subscriptable
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

4984-ERROR-Game Crash at Tue Mar 22 19:59:42 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 139, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer)
TypeError: medal_navigation() missing 1 required positional argument: 'timer'
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1960-ERROR-Game Crash at Tue Mar 22 20:01:50 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 139, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer, timer)
TypeError: medal_navigation() takes 2 positional arguments but 3 were given
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

8140-ERROR-Game Crash at Tue Mar 22 20:02:13 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 139, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\menus\medal_milestone_menu.py", line 103, in medal_navigation
    return medal_selector, timer, ghost_selector
UnboundLocalError: local variable 'ghost_selector' referenced before assignment
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

9916-ERROR-Game Crash at Tue Mar 22 20:03:25 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 139, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\menus\medal_milestone_menu.py", line 103, in medal_navigation
    return medal_selector, timer, ghost_selector
UnboundLocalError: local variable 'ghost_selector' referenced before assignment
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2552-ERROR-Game Crash at Tue Mar 22 20:05:00 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 139, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\menus\medal_milestone_menu.py", line 105, in medal_navigation
    return medal_selector, timer, ghost_selector
UnboundLocalError: local variable 'ghost_selector' referenced before assignment
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

12272-ERROR-Game Crash at Tue Mar 22 20:06:32 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 139, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer)
ValueError: too many values to unpack (expected 2)
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2960-ERROR-Game Crash at Tue Mar 22 20:08:42 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 139, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\menus\medal_milestone_menu.py", line 104, in medal_navigation
    return medal_selector, timer, ghost_selector
NameError: name 'ghost_selector' is not defined
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

7112-ERROR-Game Crash at Tue Mar 22 20:10:14 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 139, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer)
ValueError: too many values to unpack (expected 2)
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

10424-ERROR-Game Crash at Tue Mar 22 20:10:54 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 109, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 87, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 65, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 139, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(selector, timer)
ValueError: too many values to unpack (expected 2)
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

15240-ERROR-Game Crash at Tue Apr 12 19:22:24 2022 (Version 0.14.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 111, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 89, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\main.py", line 66, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\game_handler.py", line 51, in update_game_state
    info_getter, game_state = engine.menus.main_menu.splash_navigator()
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\menus\main_menu.py", line 78, in splash_navigator
    pressed = engine.handle_input.menu_input()
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\handle_input.py", line 697, in menu_input
    pressed = get_keypress()
  File "c:\Users\Xnunu\Documents\GitHub\blob_ball\engine\handle_input.py", line 579, in get_keypress
    bind_xbox_360_to_player(event, detect_new_controllers, new_controller, controller_name)
UnboundLocalError: local variable 'new_controller' referenced before assignment
Game State: control_splash
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

15728-ERROR-Game Crash at Mon May  9 17:22:15 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 119, in draw_mam
    ghost_position = info_getter[4]
IndexError: list index out of range
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

16168-ERROR-Game Crash at Mon May  9 17:31:01 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 78, in handle_graphics
    draw_css(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_css.py", line 186, in draw_css
    css_blobs(game_display, p1_selector_position, p2_selector_position, p1_blob, p2_blob)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_css.py", line 110, in css_blobs
    if(not p1_selector_position[4]):
IndexError: list index out of range
Game State: css
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

8552-ERROR-Game Crash at Mon May  9 17:34:05 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 119, in draw_mam
    ghost_position = info_getter[3]
IndexError: list index out of range
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2604-ERROR-Game Crash at Mon May  9 17:36:10 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 119, in draw_mam
    ghost_position = info_getter[2]
IndexError: list index out of range
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1596-ERROR-Game Crash at Mon May  9 17:37:54 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 119, in draw_mam
    ghost_position = info_getter[4]
IndexError: list index out of range
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

3632-ERROR-Game Crash at Wed May 18 19:22:29 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 91, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 68, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\game_handler.py", line 178, in update_game_state
    game_state, info_getter = engine.menus.blob_info_menu.general_navigation()
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\menus\blob_info_menu.py", line 136, in general_navigation
    game_state = blob_selector_navigation(pressed, mouse)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\menus\blob_info_menu.py", line 80, in blob_selector_navigation
    load_individual_blob(selector_position)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_blob_info.py", line 93, in load_individual_blob
    costume_unlock = find_costume_unlock(selected_blob[2]+"/"+ i)[3]
TypeError: 'NoneType' object is not subscriptable
Game State: blob_info
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

15632-ERROR-Game Crash at Wed May 18 19:31:21 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 119, in draw_mam
    ghost_position = info_getter[4]
IndexError: list index out of range
Game State: medals
P1 Blob: water, is CPU: False
P2_Blob: rock, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

14900-ERROR-Game Crash at Sat Jun 18 10:36:40 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 119, in draw_mam
    ghost_position = info_getter[4]
IndexError: list index out of range
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

12528-ERROR-Game Crash at Sat Jun 18 10:47:21 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 119, in draw_mam
    ghost_position = info_getter[3]
IndexError: list index out of range
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

14448-ERROR-Game Crash at Sat Jun 18 12:40:57 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 119, in draw_mam
    ghost_position = info_getter[3]
IndexError: list index out of range
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

12500-ERROR-Game Crash at Sat Jun 18 12:42:05 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 91, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 68, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\game_handler.py", line 165, in update_game_state
    info_getter = engine.menus.settings_menu.settings_navigation(timer, settings, previous_screen, cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\menus\settings_menu.py", line 222, in settings_navigation
    game_state, selector_position = settings_selection_right(selector_position, settings, previous_screen, cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\menus\settings_menu.py", line 103, in settings_selection_right
    run_func[selector_position]()
KeyError: 10
Game State: settings
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

6960-ERROR-Game Crash at Sat Jun 18 13:04:12 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 88, in handle_graphics
    draw_gameplay(screen_size, game_surface, p1_blob, p2_blob, ball, game_score, timer, game_time, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_gameplay.py", line 321, in draw_gameplay
    image_cache['p1_dead_left'] = pg.transform.scale(pg.image.load(p1_blob.image_death).convert_alpha(), (120, 66))
FileNotFoundError: No such file or directory: 'C:\Users\Xnunu\Documents\Projects\Repositories\blob_ball/resources/images/blobs/arcade_blob_-1.png'.
Game State: casual_match
P1 Blob: arcade, is CPU: False
P2_Blob: boxer, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

14352-ERROR-Game Crash at Sat Jun 18 13:06:13 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 88, in handle_graphics
    draw_gameplay(screen_size, game_surface, p1_blob, p2_blob, ball, game_score, timer, game_time, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_gameplay.py", line 324, in draw_gameplay
    image_cache['p1_ability_icon'] = pg.transform.scale(pg.image.load(p1_blob.ability_icon).convert_alpha(), (70, 70))
FileNotFoundError: No such file or directory: 'C:\Users\Xnunu\Documents\Projects\Repositories\blob_ball/resources/images/ability_icons/teleport.png'.
Game State: casual_match
P1 Blob: arcade, is CPU: False
P2_Blob: king, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

4336-ERROR-Game Crash at Sat Jun 18 13:08:55 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_gameplay.py", line 325, in draw_gameplay
    image_cache['p1_ability_icon'] = pg.transform.scale(pg.image.load(p1_blob.ability_icon).convert_alpha(), (70, 70))
FileNotFoundError: No such file or directory: 'C:\Users\Xnunu\Documents\Projects\Repositories\blob_ball/resources/images/ability_icons/teleport.png'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 88, in handle_graphics
    draw_gameplay(screen_size, game_surface, p1_blob, p2_blob, ball, game_score, timer, game_time, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_gameplay.py", line 327, in draw_gameplay
    image_cache['p1_ability_icon'] = pg.transform.scale(pg.image.load("/resources/images/ui_icons/404.png").convert_alpha(), (70, 70))
FileNotFoundError: No such file or directory: '/resources/images/ui_icons/404.png'.
Game State: casual_match
P1 Blob: arcade, is CPU: False
P2_Blob: king, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1156-ERROR-Game Crash at Sat Jun 18 13:10:23 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_gameplay.py", line 325, in draw_gameplay
    image_cache['p1_ability_icon'] = pg.transform.scale(pg.image.load(p1_blob.ability_icon).convert_alpha(), (70, 70))
FileNotFoundError: No such file or directory: 'C:\Users\Xnunu\Documents\Projects\Repositories\blob_ball/resources/images/ability_icons/teleport.png'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 88, in handle_graphics
    draw_gameplay(screen_size, game_surface, p1_blob, p2_blob, ball, game_score, timer, game_time, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_gameplay.py", line 327, in draw_gameplay
    image_cache['p1_ability_icon'] = pg.transform.scale(pg.image.load(cwd+"/resources/images/ui_icons/404.png").convert_alpha(), (70, 70))
FileNotFoundError: No such file or directory: 'C:\Users\Xnunu\Documents\Projects\Repositories\blob_ball/resources/images/ui_icons/404.png'.
Game State: casual_match
P1 Blob: arcade, is CPU: False
P2_Blob: king, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

10520-ERROR-Game Crash at Sun Jun 19 12:16:55 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 119, in draw_mam
    print(info_getter[3])
IndexError: list index out of range
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

10068-ERROR-Game Crash at Sun Jun 19 12:33:11 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 122, in draw_mam
    mam_medals(game_display, selector_position)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 66, in mam_medals
    medal_image_cache, big_image_cache = load_medals(medal_image_cache, big_image_cache, directory)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 31, in load_medals
    update_mam_medals(cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\unlocks.py", line 289, in update_mam_medals
    elif location in mam_location_dict_medals and medal_unlock_dict[mam_location_dict_medals[location]]:
KeyError: 'rule_breaker'
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

12076-ERROR-Game Crash at Sun Jun 19 12:35:20 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 122, in draw_mam
    mam_medals(game_display, selector_position)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 66, in mam_medals
    medal_image_cache, big_image_cache = load_medals(medal_image_cache, big_image_cache, directory)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 31, in load_medals
    update_mam_medals(cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\unlocks.py", line 289, in update_mam_medals
    mam_display_list_medals[y][x] = ["/medals/questionMedal.png", "???", "Coming soon!"]
IndexError: list assignment index out of range
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

8712-ERROR-Game Crash at Sun Jun 19 12:37:54 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 122, in draw_mam
    mam_medals(game_display, selector_position)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 66, in mam_medals
    medal_image_cache, big_image_cache = load_medals(medal_image_cache, big_image_cache, directory)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 31, in load_medals
    update_mam_medals(cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\unlocks.py", line 289, in update_mam_medals
    mam_display_list_medals[y][x] = ["/medals/questionMedal.png", "???", "Coming soon!"]
IndexError: list assignment index out of range
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

5184-ERROR-Game Crash at Sun Jun 19 12:47:15 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 122, in draw_mam
    mam_medals(game_display, selector_position)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 66, in mam_medals
    medal_image_cache, big_image_cache = load_medals(medal_image_cache, big_image_cache, directory)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 31, in load_medals
    update_mam_medals(cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\unlocks.py", line 295, in update_mam_medals
    mam_display_list_medals[x][y] = ["/medals/questionMedal.png", "Unlock Me!", str(game_stats['matches_played']) + "/" + str(unlock_milestones[unlock_slot]) + " Matches Complete"]
IndexError: list index out of range
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

12024-ERROR-Game Crash at Sun Jun 19 12:48:27 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 122, in draw_mam
    mam_medals(game_display, selector_position)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 66, in mam_medals
    medal_image_cache, big_image_cache = load_medals(medal_image_cache, big_image_cache, directory)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 31, in load_medals
    update_mam_medals(cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\unlocks.py", line 295, in update_mam_medals
    mam_display_list_medals[x][y] = ["/medals/questionMedal.png", "Unlock Me!", "Find your way."]
IndexError: list index out of range
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

10276-ERROR-Game Crash at Sun Jun 19 14:05:16 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 122, in draw_mam
    mam_medals(game_display, selector_position)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 66, in mam_medals
    medal_image_cache, big_image_cache = load_medals(medal_image_cache, big_image_cache, directory)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 31, in load_medals
    update_mam_medals(cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\unlocks.py", line 289, in update_mam_medals
    mam_display_list_medals[y][x] = ["/medals/questionMedal.png", "???", "Coming soon!"]
IndexError: list assignment index out of range
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

11236-ERROR-Game Crash at Sun Jun 19 14:16:59 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 122, in draw_mam
    mam_medals(game_display, selector_position)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 66, in mam_medals
    medal_image_cache, big_image_cache = load_medals(medal_image_cache, big_image_cache, directory)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 38, in load_medals
    medal_image_cache[-1].append(pg.transform.scale(pg.image.load(directory+icon[0]).convert_alpha(), (91, 91)))
FileNotFoundError: No such file or directory: 'C:\Users\Xnunu\Documents\Projects\Repositories\blob_ball/resources/images/medals/'.
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

13040-ERROR-Game Crash at Sun Jun 19 14:33:13 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 39, in load_medals
    medal_image_cache[-1].append(pg.transform.scale(pg.image.load(directory+icon[0]).convert_alpha(), (91, 91)))
FileNotFoundError: No such file or directory: 'C:\Users\Xnunu\Documents\Projects\Repositories\blob_ball/resources/images/medals/'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 127, in draw_mam
    mam_medals(game_display, selector_position)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 71, in mam_medals
    medal_image_cache, big_image_cache = load_medals(medal_image_cache, big_image_cache, directory)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 43, in load_medals
    medal_image_cache[-1].append(pg.transform.scale(pg.image.load(directory+icon[0]).convert_alpha(), (91, 91)))
FileNotFoundError: No such file or directory: 'C:\Users\Xnunu\Documents\Projects\Repositories\blob_ball/resources/images/medals/'.
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

10800-ERROR-Game Crash at Sun Jun 19 14:33:55 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 39, in load_medals
    medal_image_cache[-1].append(pg.transform.scale(pg.image.load(directory+icon[0]).convert_alpha(), (91, 91)))
FileNotFoundError: No such file or directory: 'C:\Users\Xnunu\Documents\Projects\Repositories\blob_ball/resources/images/medals/'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 127, in draw_mam
    mam_medals(game_display, selector_position)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 71, in mam_medals
    medal_image_cache, big_image_cache = load_medals(medal_image_cache, big_image_cache, directory)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 43, in load_medals
    medal_image_cache[-1].append(pg.transform.scale(pg.image.load(directory+"404.png").convert_alpha(), (91, 91)))
FileNotFoundError: No such file or directory: 'C:\Users\Xnunu\Documents\Projects\Repositories\blob_ball/resources/images404.png'.
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

14168-ERROR-Game Crash at Sun Jun 19 14:34:19 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 39, in load_medals
    medal_image_cache[-1].append(pg.transform.scale(pg.image.load(directory+icon[0]).convert_alpha(), (91, 91)))
FileNotFoundError: No such file or directory: 'C:\Users\Xnunu\Documents\Projects\Repositories\blob_ball/resources/images/medals/'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 127, in draw_mam
    mam_medals(game_display, selector_position)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 71, in mam_medals
    medal_image_cache, big_image_cache = load_medals(medal_image_cache, big_image_cache, directory)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 43, in load_medals
    medal_image_cache[-1].append(pg.transform.scale(pg.image.load(directory+"/404.png").convert_alpha(), (91, 91)))
FileNotFoundError: No such file or directory: 'C:\Users\Xnunu\Documents\Projects\Repositories\blob_ball/resources/images/404.png'.
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

10236-ERROR-Game Crash at Sun Jun 19 14:35:05 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 127, in draw_mam
    mam_medals(game_display, selector_position)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 79, in mam_medals
    token_cache['ghost'] = token_cache['p1_ball'].convert_alpha()
KeyError: 'p1_ball'
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

13656-ERROR-Game Crash at Sun Jun 19 14:35:51 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 127, in draw_mam
    mam_medals(game_display, selector_position)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 108, in mam_medals
    if(selector_position[3] == 1):
IndexError: list index out of range
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

13216-ERROR-Game Crash at Sun Jun 19 14:40:29 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 92, in run
    display_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 71, in display_graphics
    dg.handle_graphics(game_state, cwd, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_graphics.py", line 123, in handle_graphics
    draw_mam(game_surface, info_getter, settings)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\resources\graphics_engine\display_medals_and_milestones.py", line 127, in draw_mam
    game_display.blit(p1_ball, ((136 * (medal_selector[0] + 1) + 1366*(1/135)), 100 * (medal_selector[1] + 1) - 25))
NameError: name 'p1_ball' is not defined
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

13088-ERROR-Game Crash at Sun Jun 19 14:42:49 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 91, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 68, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\game_handler.py", line 181, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(timer)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\menus\medal_milestone_menu.py", line 80, in medal_navigation
    for i in range(len(mam_menu_buttons)):
UnboundLocalError: local variable 'mam_menu_buttons' referenced before assignment
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

12184-ERROR-Game Crash at Sun Jun 19 14:43:36 2022 (Version 0.15.0a)
Traceback (most recent call last):
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 113, in <module>
    game_state = run(game_state)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 91, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = get_game_state(game_state, cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\main.py", line 68, in get_game_state
    return ugs(game_state, cwd)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\game_handler.py", line 181, in update_game_state
    game_state, info_getter = engine.menus.medal_milestone_menu.medal_navigation(timer)
  File "c:\Users\Xnunu\Documents\Projects\Repositories\blob_ball\engine\menus\medal_milestone_menu.py", line 78, in medal_navigation
    mam_menu_buttons = medal_menu_buttons
NameError: name 'medal_menu_buttons' is not defined
Game State: medals
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

12696-ERROR-Game Crash at Thu Sep 29 11:46:34 2022 (Version 0.16.1b)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 80, in handle_graphics
    draw_gameplay(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 439, in draw_gameplay
    draw_menu(gameplay_surface, blob)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 316, in draw_menu
    if(blob.menu['direction'] == 'left'):
AttributeError: 'Blob' object has no attribute 'menu'
Game State: casual_match
P1 Blob: joker, is CPU: False
P2_Blob: joker, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

54092-ERROR-Game Crash at Thu Sep 29 16:31:24 2022 (Version 0.16.1b)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 80, in handle_graphics
    draw_gameplay(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 447, in draw_gameplay
    draw_menu(gameplay_surface, blob)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 321, in draw_menu
    game_display.blit(image_cache['icons'][blob.status_effects['cards']['pulled'][0]], ((blob.x_pos - 100) * (1000/1366), (blob.y_pos*(382/768))))
KeyError: ''
Game State: casual_match
P1 Blob: joker, is CPU: False
P2_Blob: joker, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

52828-ERROR-Game Crash at Thu Sep 29 16:32:33 2022 (Version 0.16.1b)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 80, in handle_graphics
    draw_gameplay(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 447, in draw_gameplay
    draw_menu(gameplay_surface, blob)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 321, in draw_menu
    game_display.blit(image_cache['icons'][blob.status_effects['cards']['pulled'][0]], ((blob.x_pos - 100) * (1000/1366), (blob.y_pos*(382/768))))
KeyError: ''
Game State: casual_match
P1 Blob: joker, is CPU: False
P2_Blob: joker, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

53276-ERROR-Game Crash at Thu Sep 29 16:36:35 2022 (Version 0.16.1b)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 80, in handle_graphics
    draw_gameplay(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 447, in draw_gameplay
    draw_menu(gameplay_surface, blob)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 328, in draw_menu
    game_display.blit(image_cache['icons'][blob.status_effects['cards']['pulled'][1]], ((blob.x_pos + 25) * (1000/1366), ((blob.y_pos - 200) *(382/768))))
KeyError: ''
Game State: casual_match
P1 Blob: joker, is CPU: False
P2_Blob: joker, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

52276-ERROR-Game Crash at Thu Sep 29 23:11:37 2022 (Version 0.16.1b)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 80, in handle_graphics
    draw_gameplay(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 363, in draw_gameplay
    image_cache[pname+'blob_left'] = pg.transform.scale(pg.image.load(blob.image).convert_alpha(), (120, pg.image.load(blob.image).get_height()*0.6))
TypeError: integer argument expected, got float
Game State: casual_match
P1 Blob: joker, is CPU: False
P2_Blob: joker, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

50248-ERROR-Game Crash at Fri Sep 30 08:06:19 2022 (Version 0.16.1b)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 78, in handle_graphics
    draw_css(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_css.py", line 187, in draw_css
    css_blobs(game_display, p1_selector_position, p2_selector_position, p1_blob, p2_blob)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_css.py", line 70, in css_blobs
    blob_image_cache, big_image_cache = load_blobs(blob_image_cache, big_image_cache, directory)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_css.py", line 45, in load_blobs
    blob_image_cache[-1].append(pg.transform.scale(pg.image.load(directory+icon[0]).convert_alpha(), (91, (pg.image.load(directory+icon[0]).get_height()*.4636))))
TypeError: integer argument expected, got float
Game State: css
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

57236-ERROR-Game Crash at Fri Sep 30 08:19:56 2022 (Version 0.16.1b)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 78, in handle_graphics
    draw_css(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_css.py", line 188, in draw_css
    css_blobs(game_display, p1_selector_position, p2_selector_position, p1_blob, p2_blob)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_css.py", line 119, in css_blobs
    costume_cache[0][1] = pg.transform.scale(pg.image.load(temp_loaded).convert_alpha(), (195, temp_loaded.get_height()))
AttributeError: 'str' object has no attribute 'get_height'
Game State: css
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2136-ERROR-Game Crash at Fri Sep 30 08:27:07 2022 (Version 0.16.1b)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 124, in handle_graphics
    draw_almanac_stats_3(game_surface, settings, info_getter)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_almanac.py", line 310, in draw_almanac_stats_3
    blob = pg.transform.scale(blob, (122, 68 - (blob.height() - 68)/2))
AttributeError: 'pygame.Surface' object has no attribute 'height'
Game State: almanac_stats_page_3
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

56608-ERROR-Game Crash at Fri Sep 30 08:27:21 2022 (Version 0.16.1b)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 124, in handle_graphics
    draw_almanac_stats_3(game_surface, settings, info_getter)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_almanac.py", line 310, in draw_almanac_stats_3
    blob = pg.transform.scale(blob, (122, 68 - round((blob.height() - 68)/2)))
AttributeError: 'pygame.Surface' object has no attribute 'height'
Game State: almanac_stats_page_3
P1 Blob: [], is CPU: False
P2_Blob: [], is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

33576-ERROR-Game Crash at Fri Sep 30 08:54:59 2022 (Version 0.16.1b)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 80, in handle_graphics
    draw_gameplay(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 446, in draw_gameplay
    gameplay_surface.blit(image_cache[pname+'damage_right'], (blob.x_pos*(1000/1366), (blob_y_pos*(400/768))))
UnboundLocalError: local variable 'blob_y_pos' referenced before assignment
Game State: casual_match
P1 Blob: joker, is CPU: False
P2_Blob: joker, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

51484-ERROR-Game Crash at Fri Sep 30 09:34:35 2022 (Version 0.16.1b)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 80, in handle_graphics
    draw_gameplay(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 453, in draw_gameplay
    draw_menu(gameplay_surface, blob)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 328, in draw_menu
    game_display.blit(image_cache['icons'][blob.status_effects['cards']['pulled'][1]], ((blob.x_pos + 25) * (1000/1366), ((blob.y_pos - 200) *(382/768))))
KeyError: 'teleportspire'
Game State: casual_match
P1 Blob: joker, is CPU: False
P2_Blob: water, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

9548-ERROR-Game Crash at Fri Sep 30 09:35:07 2022 (Version 0.16.1b)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 80, in handle_graphics
    draw_gameplay(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 453, in draw_gameplay
    draw_menu(gameplay_surface, blob)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 321, in draw_menu
    game_display.blit(image_cache['icons'][blob.status_effects['cards']['pulled'][0]], ((blob.x_pos - 100) * (1000/1366), (blob.y_pos*(382/768))))
KeyError: 'pilltax'
Game State: casual_match
P1 Blob: joker, is CPU: False
P2_Blob: water, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

58816-ERROR-Game Crash at Fri Sep 30 11:58:05 2022 (Version 0.16.1b)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 117, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = ugs(game_state, cwd)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\game_handler.py", line 144, in update_game_state
    game_state, info_getter = engine.gameplay.handle_gameplay(p1_blob, p2_blob, ruleset, settings, p1_is_cpu, p2_is_cpu, p1_costume, p2_costume, timer)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\gameplay.py", line 214, in handle_gameplay
    cpu_logic, cpu_memory = engine.cpu_logic.handle_logic_beta(p2_blob, p1_blob, ball, game_score, game_info['time'])
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\cpu_logic.py", line 386, in handle_logic_beta
    ability_dict[blob.species](blob, other_blob, ball, pressed)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\cpu_logic.py", line 212, in water_blob
    elif(blob.player == 2 and ball.x_speed > 10 and (ball.y_speed > -15 or ball.y_pos > 925) and (blob.special_ability_meter > blob.special_ability_cost * 2.5 or blob.holding_timer > 0 or ball.x_pos > 1505)):
AttributeError: 'Blob' object has no attribute 'holding_timer'
Game State: casual_match
P1 Blob: joker, is CPU: False
P2_Blob: water, is CPU: True

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

81768-ERROR-Game Crash at Wed Oct  5 13:39:26 2022 (Version 0.17.0a)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 80, in handle_graphics
    draw_gameplay(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 449, in draw_gameplay
    draw_blob_particles(gameplay_surface, blobs.values()) # TODO: Fix this!
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_particles.py", line 141, in draw_blob_particles
    for icon in ability_image_dict:
NameError: name 'ability_image_dict' is not defined
Game State: casual_match
P1 Blob: joker, is CPU: False
P2_Blob: joker, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

72192-ERROR-Game Crash at Wed Oct  5 13:39:59 2022 (Version 0.17.0a)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 80, in handle_graphics
    draw_gameplay(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 449, in draw_gameplay
    draw_blob_particles(gameplay_surface, blobs.values()) # TODO: Fix this!
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_particles.py", line 213, in draw_blob_particles
    if(blob.status_effects['menu']['joker_particle']):
KeyError: 'joker_particle'
Game State: casual_match
P1 Blob: joker, is CPU: False
P2_Blob: joker, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

15832-ERROR-Game Crash at Wed Oct  5 13:41:39 2022 (Version 0.17.0a)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 80, in handle_graphics
    draw_gameplay(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 449, in draw_gameplay
    draw_blob_particles(gameplay_surface, blobs.values()) # TODO: Fix this!
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_particles.py", line 214, in draw_blob_particles
    draw_card_selection(*blob.status_effects['menu']['joker_particle'])
KeyError: 'joker_particle'
Game State: casual_match
P1 Blob: joker, is CPU: False
P2_Blob: joker, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

6676-ERROR-Game Crash at Wed Oct  5 13:42:08 2022 (Version 0.17.0a)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 80, in handle_graphics
    draw_gameplay(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 449, in draw_gameplay
    draw_blob_particles(gameplay_surface, blobs.values()) # TODO: Fix this!
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_particles.py", line 214, in draw_blob_particles
    draw_card_selection(*blob.status_effects['menu']['joker_particle'])
KeyError: 'joker_particle'
Game State: casual_match
P1 Blob: joker, is CPU: False
P2_Blob: joker, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

41412-ERROR-Game Crash at Wed Nov 30 14:53:26 2022 (Version 0.17.0a)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 117, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = ugs(game_state, cwd)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\game_handler.py", line 144, in update_game_state
    game_state, info_getter = engine.gameplay.handle_gameplay(p1_blob, p2_blob, ruleset, settings, p1_is_cpu, p2_is_cpu, p1_costume, p2_costume, timer)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\gameplay.py", line 189, in handle_gameplay
    blobs = initialize_players(p1_selected, p2_selected, ruleset, settings, p1_is_cpu, p2_is_cpu, p1_costume=p1_costume, p2_costume=p2_costume)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\gameplay.py", line 27, in initialize_players
    p1_blob = engine.blobs.Blob(species = p1_selected, player = 1, x_pos = 100, facing = 'right', special_ability_charge_base = ruleset['special_ability_charge_base'], danger_zone_enabled = ruleset['danger_zone_enabled'], is_cpu = p1_is_cpu, stat_overrides = ruleset['p1_modifiers'], costume = p1_costume)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\blobs.py", line 126, in __init__
    self.ability_icon = species_to_ability_icon(species)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\blob_stats.py", line 111, in species_to_ability_icon
    return ability_image_dict[species]
KeyError: 'taco'
Game State: casual_match
P1 Blob: taco, is CPU: False
P2_Blob: taco, is CPU: True

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

13804-ERROR-Game Crash at Thu Dec  1 11:33:58 2022 (Version 0.17.0a)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 80, in handle_graphics
    draw_gameplay(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 452, in draw_gameplay
    draw_menu(gameplay_surface, blob)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 320, in draw_menu
    game_display.blit(image_cache['icons'][blob.status_effects['cards']['pulled'][0]], ((blob.x_pos - 100) * (1000/1366), (blob.y_pos*(382/768))))
IndexError: list index out of range
Game State: casual_match
P1 Blob: taco, is CPU: False
P2_Blob: taco, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

11052-ERROR-Game Crash at Sun Dec  4 19:29:26 2022 (Version 0.17.0a)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 118, in run
    dg.handle_graphics(game_state, cwd, info_getter, settings) # Graphics always lag behind by a single frame
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_graphics.py", line 80, in handle_graphics
    draw_gameplay(game_surface, info_getter, settings)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_gameplay.py", line 494, in draw_gameplay
    draw_blob_particles(gameplay_surface, blobs.values()) # TODO: Fix this!
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\resources\graphics_engine\display_particles.py", line 161, in draw_blob_particles
    blob_traction += 1
UnboundLocalError: local variable 'blob_traction' referenced before assignment
Game State: casual_match
P1 Blob: taco, is CPU: False
P2_Blob: taco, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

6504-ERROR-Game Crash at Sun Dec 18 08:23:40 2022 (Version 0.17.0a)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 117, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = ugs(game_state, cwd)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\game_handler.py", line 144, in update_game_state
    game_state, info_getter = engine.gameplay.handle_gameplay(p1_blob, p2_blob, ruleset, settings, p1_is_cpu, p2_is_cpu, p1_costume, p2_costume, timer)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\gameplay.py", line 212, in handle_gameplay
    movement_string += convert_inputs_to_replay(p1_blob.move(pressed), 1)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\blobs.py", line 1629, in move
    self.ability()
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\blobs.py", line 901, in ability
    create_environmental_modifier(player = self.player, affects = {'enemy', 'ball'}, species = 'spike', lifetime = special_ability_delay, y_pos = 700)
UnboundLocalError: local variable 'special_ability_delay' referenced before assignment
Game State: casual_match
P1 Blob: cactus, is CPU: False
P2_Blob: cactus, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

16360-ERROR-Game Crash at Sun Dec 18 09:06:04 2022 (Version 0.17.0a)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 117, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = ugs(game_state, cwd)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\game_handler.py", line 144, in update_game_state
    game_state, info_getter = engine.gameplay.handle_gameplay(p1_blob, p2_blob, ruleset, settings, p1_is_cpu, p2_is_cpu, p1_costume, p2_costume, timer)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\gameplay.py", line 231, in handle_gameplay
    sball.check_environmental_collisions(env_mod)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\ball.py", line 384, in check_environmental_collisions
    hazard_vector = pg.math.Vector2(hazard.x_center, hazard.y_center)
AttributeError: 'EnvironmentalModifiers' object has no attribute 'x_center'
Game State: casual_match
P1 Blob: cactus, is CPU: False
P2_Blob: cactus, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

4032-ERROR-Game Crash at Sun Dec 18 09:06:43 2022 (Version 0.17.0a)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 117, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = ugs(game_state, cwd)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\game_handler.py", line 144, in update_game_state
    game_state, info_getter = engine.gameplay.handle_gameplay(p1_blob, p2_blob, ruleset, settings, p1_is_cpu, p2_is_cpu, p1_costume, p2_costume, timer)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\gameplay.py", line 231, in handle_gameplay
    sball.check_environmental_collisions(env_mod)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\ball.py", line 397, in check_environmental_collisions
    if(dist_vector.length > 150):
AttributeError: 'float' object has no attribute 'length'
Game State: casual_match
P1 Blob: cactus, is CPU: False
P2_Blob: cactus, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

17444-ERROR-Game Crash at Sun Dec 18 09:31:20 2022 (Version 0.17.0a)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 117, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = ugs(game_state, cwd)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\game_handler.py", line 144, in update_game_state
    game_state, info_getter = engine.gameplay.handle_gameplay(p1_blob, p2_blob, ruleset, settings, p1_is_cpu, p2_is_cpu, p1_costume, p2_costume, timer)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\gameplay.py", line 228, in handle_gameplay
    blob.check_environmental_collisions(env_mod)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\blobs.py", line 1235, in check_environmental_collisions
    if(hazard.player != self.player and 'enemy' in hazard.affects and self.player not in hazard):
TypeError: argument of type 'EnvironmentalModifiers' is not iterable
Game State: casual_match
P1 Blob: cactus, is CPU: False
P2_Blob: quirkless, is CPU: True

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

19144-ERROR-Game Crash at Sun Dec 18 09:47:46 2022 (Version 0.17.0a)
Traceback (most recent call last):
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 146, in <module>
    game_state = run(game_state)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\main.py", line 117, in run
    new_game_state, info_getter, bgm_song, settings, ruleset = ugs(game_state, cwd)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\game_handler.py", line 144, in update_game_state
    game_state, info_getter = engine.gameplay.handle_gameplay(p1_blob, p2_blob, ruleset, settings, p1_is_cpu, p2_is_cpu, p1_costume, p2_costume, timer)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\gameplay.py", line 228, in handle_gameplay
    blob.check_environmental_collisions(env_mod)
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\blobs.py", line 1244, in check_environmental_collisions
    self.take_damage(damage = 1, stun_amount = stun_amount, status_effects = ['nrg_drain', 300])
  File "C:\Users\Elijah McLaughlin\Documents\GitHub\blob_ball\engine\blobs.py", line 1322, in take_damage
    self.status_effects[status_effect[0]] += status_effect[1]
KeyError: 'n'
Game State: casual_match
P1 Blob: cactus, is CPU: False
P2_Blob: cactus, is CPU: False

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

